id = "falcon-theme"
name = "Falcon Relaxing-Eyes Themes"
version = "1.0.10"
schema_version = 1
authors = ["Panxiaoan 🍃"]
description = "🦅 A gentle, eye-friendly themes to protect your eyesight for Zed. 一个温和的，对眼睛友好，保护视力的 Zed 护眼主题。"
repository = "https://github.com/panxiaoan/falcon-zed-themes"
